/** @format */

import type { PlaceType, IMenu } from '../models/models';

export const allTypes: PlaceType[] = [
    'all',
    'Museum',
    'Hospital',
    'Church',
    // 'Shop',
    'Police',
    'Airport',
    'Park',
    'Library',
    'Theatre',
    'Cafe',
    'Hotel',
];

export const translations: IMenu = {
    en: {
        more: 'More details',
        all: 'All',
        Museum: 'Museum',
        // Cafe: 'Cafe & Restaurant',
        Hospital: 'Hospital',
        Church: 'Church',
        // Shop: 'Shop',
        Police: 'Police',
        Airport: 'Airport',
        Park: 'Park',
        Library: 'Library',
        Theatre: 'Theatre',
        Cafe: 'Cafe',
        Hotel: 'Hotel',
    },
    ru: {
        more: 'Подробнее',
        all: 'Все',
        Museum: 'Музей',
        // Cafe: 'Кафе и Ресторан',
        Hospital: 'Больница',
        Church: 'Церковь',
        // Shop: 'Магазин',
        Police: 'Полиция',
        Airport: 'Аэропорт',
        Park: 'Парк',
        Library: 'Библиотека',
        Theatre: 'Театр',
        Cafe: 'Кафе',
        Hotel: 'Отель',
    },
    hy: {
        more: 'Մանրամասներ',
        all: 'Բոլորը',
        Museum: 'Թանգարան',
        // Cafe: 'Սրճարան և Ռեստորան',
        Hospital: 'Հիվանդանոց',
        Church: 'Եկեղեցի',
        // Shop: 'Խանութ',
        Police: 'Ոստիկանություն',
        Airport: 'Օդանավակայան',
        Park: 'Այգի',
        Library: 'Գրադարան',
        Theatre: 'Թատրոն',
        Cafe: 'Սրճարան',
        Hotel: 'Հյուրանոց',
    },
};
